conf_upload.cgi : conf_upload.c cgic.h cgic.c
	/opt/hisi-linux/x86-arm/arm-hisiv600-linux/target/bin/arm-hisiv600-linux-gcc -Wall  conf_upload.c cgic.c -o conf_upload.cgi
clean:
	rm  conf_upload.cgi*
